### ISSUE TITLE
No Damage when using groupSave macro

### ISSUE THREAD

**Issue by Mr-Monocyte** [Djphoenix719/FVTT-PF2EToolbox#27]
**Describe the bug**
When I use the groupSave macro to roll saves for NPCs, I input a damage value. The resulting chat box output doesn't show any damage value or buttons to apply that damage.

**To Reproduce**
1. Select 1 or more NPCs
2. Click on the Group Saving Throw macro provided in the compendium for PF2e Toolbox
3. Fill in the dialog box with Save type, DC and Damage
4. See chat message with Save rolls and interpreted results (Fail, Critical Success, etc...) but no damage values/buttons

**Expected behavior**
At step 4, to see a chat message with both saves and damage values/buttons.

**Version Information:**
 - Browser: Chrome version 88.0.4324.150
 - FoundryVTT version 0.7.9
 - System: Pathfinder 2nd Edition version 1.11.5.3707
 - PF2E Toolbox version 1.6.0
 - No other modules active

**Additional context**

This behavior occurs even when PF2e Toolbox is the only active module.

**Comment by Mr-Monocyte** [comment]
![2021-02-11](https://user-images.githubusercontent.com/68182688/107686039-91dcfc00-6c59-11eb-8112-83b10ac52c19.png)

**Comment by Djphoenix719** [comment]
Hey @Mr-Monocyte - I am unable to reproduce this behavior. Can you export the NPCs you are having issue with and upload them so I may see if it is something with the NPC?

**Comment by Mr-Monocyte** [comment]
Ok, I believe I've figured it out. I was getting that bug because the scene I was testing the NPCs in wasn't **ACTIVE**. When I activated the scene, everything worked as expected!

**Comment by Djphoenix719** [comment]
Ok, thanks! I will address that in a future update!
