### ISSUE TITLE
Incorrect values for Precious Materials in Create Item

### ISSUE THREAD

**Issue by shandrakor** [Djphoenix719/FVTT-PF2EToolbox#28]
The weapon/armor creator takes values for special materials from the tables on page 578-579, which are the values of a "simple
non-magical item made of that material." These prices do not apply to weapons and armor. 

"Prices for armor, shields, and weapons made of precious material are in the Armor (page 555), Shields (page 586), and Weapons (page 599) sections of this chapter."

**Comment by Djphoenix719** [comment]
Fixed in LootGen
