### ISSUE TITLE
Conflict between this module and modules that edit the character sheet title bar

### ISSUE THREAD

**Issue by zarmstrong** [Djphoenix719/FVTT-PF2EToolbox#29]
Hey, I'm the author of the Hero Lab import tool. It was brought to my attention that my module's button disappeared from the character sheet title bar. After testing a bunch of modules, it turns out its this module that breaks it. It also breaks GM Notes module by preventing the button from being displayed.

I haven't looked too deeply yet, as I'm about to run a game, but this broke recently. I'm not sure if the issue lies in my code or in yours.

**Comment by Djphoenix719** [comment]
This should be fixed in next update, there was an issue preventing hooks from being called. I'll be pushing it tonight or tomorrow.
