### ISSUE TITLE
error loading FVTT

### ISSUE THREAD

**Issue by BoTKaPyC** [Djphoenix719/FVTT-PF2EToolbox#35]
when loading the world I created, an error immediately crashes in the console. I use the PF 2e system
![Без имени](https://user-images.githubusercontent.com/80960291/111778147-08fb5500-88d6-11eb-8f6d-80feccc1052c.png)

**Comment by erithtotl** [comment]
This is because the name of this sheet has been changed to LootSheetPF2e in the core system.

Also, should probably have that in a constants file rather than hardcoded in the main script file.
