### ISSUE TITLE
Loot Sheet Problems

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Djphoenix719/FVTT-PF2EToolbox#37]
**Describe the bug**
Can't access the Configure Loot section of the pf2etoolbox loot sheet. Further existing loot sheet in my other game 

**To Reproduce**
1. Create game/load in Toolbox by itself.
2. Create a Loot sheet, set it to the PF2eToolbox loot sheet.
3. Click on Configure Loot

**Expected behavior**
Should be bringing up the tabbed sections of useful tools like random treasure objects and creating properly priced magical weapons.

**Screenshots**
![image](https://user-images.githubusercontent.com/24766235/116955470-40d91480-ac58-11eb-8f88-59ef4fd9b64d.png)

When I try to set a loot sheet to your version of the sheet I noticed this error:

![image](https://user-images.githubusercontent.com/24766235/116955631-b2b15e00-ac58-11eb-9c60-9da5d3ef5e75.png)

When loading a existing loot sheet in my other game I get this error:

![image](https://user-images.githubusercontent.com/24766235/116955568-8c8bbe00-ac58-11eb-9870-4f78d128fe63.png)

**Version Information:**
 - FoundryVTT [e.g. 0.7.9]
 - PF2E Toolbox [e.g. 1.7.1]
 - Pathfinder 2e [1.13.2.5430]

**Additional context**

**Comment by Djphoenix719** [comment]
Thanks @Cosmic-Lattee - it is likely an update to the PF2E system that broke it, I'll take a look at it soon.

**Comment by Cosmic-Lattee** [comment]
I imagined that was what happened. A few of the modules were acting a little screwy. Thanks!
