### ISSUE TITLE
Remove Default Art

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Djphoenix719/FVTT-PF2EToolbox#38]
**Describe the bug**
Enabling the remove default art doesn't seem to do anything. When I look at the monsters after a import them they still have the default art tokens even after a reload. No errors appear in the log as far as I can see.

**To Reproduce**
1. Create a fresh game, load only Toolbox as a module.
2. Turn on the Remove Default Art.
3. Reload the program.
4. Import the Goblin Warrior and check the Prototype Token page.

**Expected behavior**
I assume this should set it to "icons/svg/mystery-man.svg" unless I am misunderstanding what this part of the module is supposed to do.

**Screenshots**
![image](https://user-images.githubusercontent.com/24766235/116956236-5d764c00-ac5a-11eb-9513-bcb3811e18fb.png)

**Version Information:**
 - FoundryVTT [e.g. 0.7.9]
 - PF2E Toolbox [e.g. 1.7.1]
 - Pathfinder 2e [1.13.2.5430]

**Additional context**

**Comment by Djphoenix719** [comment]
Hi @Cosmic-Lattee - this appears to be working with the new version of PF2E (1.14.0.5521), although it appears to take a refresh of the page to fully complete. Note it only removes default artwork in the compendium packs (and as such in newly imported creatures). If you do not see this behavior working still, let me know by re-opening this issue. Thanks!
