### ISSUE TITLE
Area damage level scaler

### ISSUE THREAD

**Issue by Lendala** [Djphoenix719/FVTT-PF2EToolbox#4]
Most monsters with area damage have their area damage abilities scaled very weirdly. On some creatures like the sea drake it scales it with strike dmg instead of the area dmg table but with others it scales even weirder such as an adult magma dragon. I don't know if it is possible to have the module recognize area damage properly but I thought I would bring it up.

**Comment by Djphoenix719** [comment]
Definitely an error on my part, will fix today.
