### ISSUE TITLE
Creature Builder isn't working

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Djphoenix719/FVTT-PF2EToolbox#41]
**Describe the bug**
Creature builder is no longer appearing on the menu 

**To Reproduce**
1. Update to 0.8.6 Foundry, 2.0.2.5814 PF2E, and 1.7.2 Toolbox.
2. Open a NPC sheet/create a NPC sheet.

**Expected behavior**
You should see the creature builder when it is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/24766235/120398324-99efa300-c2ff-11eb-9832-a5335536c548.png)

**Version Information:**
Foundry 0.8.6
PF2E 2.0.2.5814
Toolbox 1.7.2

**Additional context**

**Comment by Djphoenix719** [comment]
@Trollderim - I fixed the button not appearing but the builder itself needs refactoring for 0.8.x

**Comment by Cosmic-Lattee** [comment]
Gotcha makes sense. 0.8 changed a lot of stuff. The Scale to Level tool doesn't work either. Imagine that is also because of the 0.8 changes.

**Comment by Djphoenix719** [comment]
Working on that right now. Everything except the creature builder should be done shortly.
