### ISSUE TITLE
Lootsheet - Treasure change the value to the minimal

### ISSUE THREAD

**Issue by Danscath** [Djphoenix719/FVTT-PF2EToolbox#45]
**Foundry version:** 0.8.6. 
**PF2 system version:** 2.2.0.6097

When I roll for a new treasure, the item always get the minimal value of that option. On the screenshot, I press roll 1 from the rectangle red, then I get one "Porcelain vase inlaid with gold" on loot sheet with value of 25gp then go to chat and click on the "Porcelain vase inlaid with gold" item from the chat to open the item info sheet and the value's 75gp

![Screenshot_6](https://user-images.githubusercontent.com/38579689/121809851-c5a74d00-cc5e-11eb-8fe3-53514de7dbf8.png)

**Comment by Djphoenix719** [comment]
Hi @Danscath - this is intentional, and how Foundry works when you draw items from rollable tables. The link in chat links to the original item in the compendium, while the item on the sheet is the modified copy with adjusted treasure value.
