### ISSUE TITLE
Toolbox casts invisibility on prepared spells

### ISSUE THREAD

**Issue by b-r-i-an** [Djphoenix719/FVTT-PF2EToolbox#46]
**Describe the bug**
Prepared spellcasting slots disappear and are replaced by spellbook spells.

**To Reproduce**
1. Create a brand new npc
2. Use creature builder and give a spellcasting level of anything other that none
3. Add any prepared spellcasting type
4. Add a spell of any level
5. Close the character sheet
6. Open the character sheet

**Expected behavior**
Not hide all the prepared spells spells.

**Screenshots**
![image](https://user-images.githubusercontent.com/26179509/123534677-c45d3200-d6ec-11eb-894e-f20134a0b5eb.png)

**Version Information:**
 - Firefox Developer Edition 90.0b12 64-bit
 - FoundryVTT [e.g. 0.8.8]
 - PF2E Toolbox [e.g. 1.7.5]
 - Activated Systems & Modules w/ Versions
   - too many

**Additional context**
Reported in [base system](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/1467) as well may be base system related but is only reproduce able by using toolbox features.

**Comment by Djphoenix719** [comment]
@Trollderim Seems to be related to a update with PF2E.

**Comment by Trollderim** [comment]
@Djphoenix719 According to the [issue](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/1467) in the base system, this seems fixed.
