### ISSUE TITLE
Created Items from the Loot Sheet break PC sheets

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [Djphoenix719/FVTT-PF2EToolbox#47]
I've recently updated from 0.7.10 to 0.8.8 and found that all items created by the loot sheet completely break automation for characters.

I've reached out in discord and there seem to be lots of changes in the item structure. Here's a link to the first reply, a few follow after: https://discord.com/channels/170995199584108546/697845559435853865/862754778203291669
(Some notes: range is "" instead of "melee" no price, some null <--> "" mismatches)

I tested it with a newly created item, and that has the same issues. So it seems to me an update to the new item structure is in order? And a macro that "fixes" old items?

**Comment by Djphoenix719** [comment]
Yes I am aware of this and working on reworking it as part of a substantial improvement. At the moment do not use the item creator, the loot rollers should work fine as is. You can fix the sheets by deleting custom items created with the weapon/armor creator.

I will include a macro that fixes old items. Hopefully by the end of the weekend I can have a version 1 out.

Thanks!

**Comment by TiloBuechsenschuss** [comment]
Great, looking forward to it. I've placed a lot of items in loot boxes in my world. :-) 👍

**Comment by Djphoenix719** [comment]
@TiloBuechsenschuss The new version of Toolbox should automatically fix your items. You can also type `/pf2e-toolbox fix-materials` in chat to run the fix script automatically.
