### ISSUE TITLE
Toolbox wont work!

### ISSUE THREAD

**Issue by viniciusaraujo093** [Djphoenix719/FVTT-PF2EToolbox#48]
Toolbox wont work on new Pathfinder 2e Version[2.9.1.6656], doesnt show modules options and not showing Loot, macros none of 3 are working.

![image](https://user-images.githubusercontent.com/57771177/125186895-395b5c00-e203-11eb-9d7f-0ae2e36def52.png)

 - Browser: Google Chrome [91.0.4472.124]
 - FoundryVTT [0.8.8]
 - PF2E Toolbox [1.7.8]
 - Only Find The Culprit

**Comment by Djphoenix719** [comment]
Hi @viniciusaraujo093 - an error with my CI caused the script to fail to be packaged with the zip. It should be working now if you update. Sorry for the inconvenience!
