### ISSUE TITLE
Incopatibility with Dice Tray 1.0.0

### ISSUE THREAD

**Issue by apoapostolov** [Djphoenix719/FVTT-PF2EToolbox#49]
Dice Tray 1.0.0 was released today with many changes and 0.8.8 support, but it is in conflict with PF2 Toolbox. 

When both mods are on, Dice Tray buttons no longer roll any dice.

The issue is also reported on Dice Tray tracker: https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator/-/issues/26

**Comment by Djphoenix719** [comment]
Fixed in 1.7.10
