### ISSUE TITLE
NPC Sanitiser for Proficiency without Level

### ISSUE THREAD

**Issue by SergioCaptio** [Djphoenix719/FVTT-PF2EToolbox#5]
I am planning to play using the proficiency without level rule variant and I belive that your module comes in handy.
If I set a monster at level 0, the level bonus disappears from armor class, attack rolls and so on. It's cool and easy to use. I only have to restore the base hp to get the creature I need, I think and hope.
I haven't look in to the code or the scaling rules, but my understanding is that your module also changes the strike damage and ability scores, if I don't manually restore them I risk to have weaker creatures. It's not a real problem, I am lazy and I would rather have a weaker creature than to manually correct all bonuses of all creatures in the compendium. So, thanks for the module. However if someday you put a checkbox in the settings to remove the hp, ability and damage dice scaling to support the variant rule, I would much appreciate.

Cheers,
A non-english speaker and Pathfinder 2e player.

**Comment by Djphoenix719** [comment]
I might get to this but proficiency without level is going to be added to core pf2e for NPCs eventually I've been told so it might be best to wait until then.

**Comment by Djphoenix719** [comment]
Closing this - flatten proficiency is included since a version or two ago.
