### ISSUE TITLE
PF2e toolbox setting menu not opening

### ISSUE THREAD

**Issue by Symon-S** [Djphoenix719/FVTT-PF2EToolbox#51]
This error is displayed when trying to open PF2e toolbox settings
PF2e vs 2.10
foundry 0.8.8
PF2e toolbox 1.7.12

![image](https://user-images.githubusercontent.com/81383360/126726333-0501c620-c307-449a-b658-4b144c6998ce.png)

**Comment by Djphoenix719** [comment]
Fixed in 1.7.13
