### ISSUE TITLE
Attack Window isn't showing titles of modifiers

### ISSUE THREAD

**Issue by Strangley-Browne** [Djphoenix719/FVTT-PF2EToolbox#52]
![image](https://user-images.githubusercontent.com/87890230/126859153-a078fa28-f2a7-46f2-b469-45bfcdd4c87c.png)
![image](https://user-images.githubusercontent.com/87890230/126859228-3e77f793-a9ea-43a1-be6e-ae771c17ea9a.png)

No errors in the console

**Comment by Djphoenix719** [comment]
Fixed in PF2E Lootgen v1.0.2

**Comment by Strangley-Browne** [comment]
> Fixed in PF2E Lootgen v1.0.2

Cool!
