### ISSUE TITLE
Lastest update results in menus getting duplicated

### ISSUE THREAD

**Issue by erithtotl** [Djphoenix719/FVTT-PF2EToolbox#54]
Since the latest update, 'Creature Builder' on the NPC sheet, as well as the 'Scale to level' and 'Flatten NPC' context menus are displayed twice.

![image](https://user-images.githubusercontent.com/18316783/127747611-a85b2b52-5254-42bd-afae-d1be8a250dab.png)

Attached is a fix I did in bundle.js to check for duplicates.  Obviously the right solution is to find out why its getting added twice ahead of time but in the meantime if anyone wants to use the attached go ahead.
[bundle.zip](https://github.com/Djphoenix719/FVTT-PF2EToolbox/files/6911560/bundle.zip)

**Comment by Djphoenix719** [comment]
Fixed in 1.7.14
