### ISSUE TITLE
Distribute Hero Point macro doesn't work

### ISSUE THREAD

**Issue by tristerfalm** [Djphoenix719/FVTT-PF2EToolbox#59]
Maybe from the new PF2E update, I don't know, but the macro to add Hero points doesn't do anything. I click it, type in 1, nothing's added. No console errors that I see, even with debug module. Possibly related to: if I right-click a dice roll result box and click "Reroll using a Hero Point" it will reroll but will also not subtract a Hero point.

**Comment by tristerfalm** [comment]
Ok, PF2E updated this morning and fixed the reroll Hero Point issue, but Toolbox needs to adjust "data.attributes.heroPoints.rank" to "data.resources.heroPoints.value". Seems the property names changed

**Comment by Djphoenix719** [comment]
Yes I will correct this ASAP, I only have a few weeks of grad school left
then I can do a full update of the module.
