### ISSUE TITLE
Module stopped working?

### ISSUE THREAD

**Issue by Arborerivus** [Djphoenix719/FVTT-PF2EToolbox#61]
**Describe the bug**
The module seems to have stopped working out of the blue, other than the compendium folder I do not see any of your modules function in my world.
I already deactivated some modules that i had not used together with this module before, but no success...

**Version Information:**
 - Edge
 - FoundryVTT 0.89 on the Forge
 - PF2E Toolbox 
 - Activated Systems & Modules w/ Versions

![image](https://user-images.githubusercontent.com/96127307/146017072-2bbc1125-9f78-42ae-b671-8e09e94f36a6.png)

**Comment by Djphoenix719** [comment]
Hi @Arborerivus - could you try to uninstall and reinstall the module and see if that fixes it? Additionally ensure you have the options you want enabled in the module settings. I am unable to reproduce this locally so I want to ensure it is not on your end.
