### ISSUE TITLE
Toolbox 1.7.16 on PF2e 3.0.1.9499 appears to be breaking Actor context menu

### ISSUE THREAD

**Issue by galaara98** [Djphoenix719/FVTT-PF2EToolbox#63]
**Describe the bug**
when module is enabled Actor do not show context menu (right click on actor to delete, etc.)

**To Reproduce**
1. Given the versions below, if ONLY this module is enabled (and loot-generator)
2. Right click on an actor
3. No Menu appears

**Expected behavior**
Well, when this mod is not active (even if Loot-Generator is), i get the menu... I would expect to get the menu when this mod is active :)

**Screenshots**
Note: Screenshot show lots of other modules, however I tried it with JUST Toolbox (and Loot Generator) and it fails the same way.

**Version Information:**
 - Browser Edge 96 (Chromium) 
 - FoundryVTT Stable 9, Build 238
 - PF2e System: 3.0.1.9499
 - PF2E Toolbox 1.7.16
 - Activated Systems & Modules w/ Versions: Only PF2E Toolbox and PF2E Loot Generator 1.0.3
 -     When PF2E Loot Generator 1.0.3 is enabled by itself, there is no issues

**Additional context**
![image](https://user-images.githubusercontent.com/178406/147284018-426a637e-21f0-4fe4-8367-df6990568f4e.png)
![image](https://user-images.githubusercontent.com/178406/147283623-30c1f54c-20bd-4c2b-94a5-2b7e1ad66c3b.png)

**Comment by Djphoenix719** [comment]
Thanks for the heads up, I'll take a look at this over the weekend.

**Comment by galaara98** [comment]
When I RightClick on Actor (from Browser f12 console):


foundry.js:4621 Foundry VTT | Retrieved and compiled template /modules/token-action-hud/templates/template.hbs
NPCScaler.ts:29 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'data')
[Detected 1 package: pf2e-toolbox]
    at Object.condition (NPCScaler.ts:29)
    at ContextMenu.render (foundry.js:43494)
    at HTMLLIElement.<anonymous> (foundry.js:43437)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.v.handle (jquery.min.js:2)
condition @ NPCScaler.ts:29
render @ foundry.js:43494
(anonymous) @ foundry.js:43437
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:3022 Foundry VTT | Rendering ActorDirectory
foundry.js:4621 Foundry VTT | Retrieved and compiled template templates/app-window.html

**Comment by galaara98** [comment]
disabling NPCScaler and restarting game (browser f5) allows the module to be enabled and the menu to work
I mean, i still can't wait for you to check it out, since I do enjoy the NPC scaler .. but the error above and this info points to that sub component injecting its menu item into actors

**Comment by galaara98** [comment]
Thank you... for everything!  I hope this comment doesn't reopen the issue, but I really wanted you to know:  I care, and the community appreciates your mods!!!

**Comment by Djphoenix719** [comment]
Thanks a ton! Happy gaming! :)
