### ISSUE TITLE
Removed Feature Native Implementation: Distribute XP

### ISSUE THREAD

**Issue by dpotter895** [Djphoenix719/FVTT-PF2EToolbox#69]
I use to use the DistributeXp class that you made to automatically give my players xp based on the battle outcome. I found the commit where you removed this class, and you say you did this because native already provides this functionality. I can't seem to find any documentation on this, could you either point me to where you found this info or give me an example of native implementation, if you don't mind?
(I also see it says it is still supported in the Readme).

**Comment by Djphoenix719** [comment]
PF2E provides a macro in the pack of macros that comes with the system.

**Comment by Wasabi2007** [comment]
Could you point me to where to find the Systems distribute XP macro 🙂
I only seem to find the calculate XP macro 😅

**Comment by dpotter895** [comment]
I had to make my own distribution of xp. I based it off the distribute hero points macro.
