### ISSUE TITLE
Loot Generator doesn't work with permanent items

### ISSUE THREAD

**Issue by Shandyan** [Djphoenix719/FVTT-PF2EToolbox#9]
If I try and add permanent items to the loot sheet you've added, I get the following error message:
![image](https://user-images.githubusercontent.com/63457907/92102241-42ef8880-edd6-11ea-8943-de0a60f48bde.png)
This doesn't appear to happen with every possible level/number combination, but triggers e.g. for roll 2 2nd level items.

**Comment by Djphoenix719** [comment]
This is caused by bad rollable tables in PF2E. They should be updating soon, at which point it will fix itself.
